PREFIX dc_elements: <http://purl.org/dc/elements/1.1/>
PREFIX dc_terms: <http://purl.org/dc/terms/>

SELECT ?subject ?orcid
WHERE {
  ?subject dc_elements:contributor|dc_terms:contributor ?orcid .
  FILTER(!regex(str(?orcid), "^(https://orcid.org/)[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}(?:[0-9]|X)"))
}