PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?term
WHERE {
  { 
    ?term a owl:Class .
  }
  UNION
  { 
    ?term a owl:ObjectProperty .
  }
  UNION
  { 
    ?term a owl:DataProperty .
  }
  FILTER(isIRI(?term))
}
